---
title: "Productivity Model Simulations - Oregon Test"
author: "J.R. Blaszczak, C.B. Yackulic, R.K. Shriver, R.O. Hall, Jr."
output: html_document
---

```{r,echo=FALSE,warning=FALSE,message=FALSE, include=FALSE}
## See simulation_matrix_output.R for code to create figures

# load packages
lapply(c("plyr","dplyr","ggplot2","cowplot","lubridate",
         "parallel","tidyverse","rstan",
         "bayesplot","shinystan","Metrics","MCMCglmm"), require, character.only=T)

## Source data
source("Oregon_ClackamasData_Source.R")
df <- dat$Clackamas_OR
df <- df[which(df$year == "2010"),] ## Subset to 2010
# temporary solution to turbidity data gaps
df$mean_daily_turb <- na.approx(df$mean_daily_turb, maxgap = 3)
```


#### Visualize data
```{r, warning=FALSE, echo=FALSE}
plot_grid(
 ggplot(df, aes(date, GPP))+#, ymin = GPP-GPP_sd, ymax = GPP+GPP_sd))+
    geom_point(color="chartreuse4", size=2)+
    geom_errorbar(data=df, aes(date, GPP, ymin = GPP.lower, ymax = GPP.upper), width=0.2,color="darkolivegreen4")+
    labs(y=expression('GPP (g '*~O[2]~ m^-2~d^-1*')'))+
    theme(legend.position = "none",
          panel.background = element_rect(color = "black", fill=NA, size=1),
          axis.title.x = element_blank(), axis.text = element_text(size=13),
          axis.title.y = element_text(size=15)),
  
  ggplot(df, aes(date, tQ*1))+geom_line(size=1.5, color="deepskyblue4")+
    geom_point(data=df, aes(date, light_rel), size=2, color="darkgoldenrod3")+
    scale_y_continuous(sec.axis = sec_axis(~./1, name=expression("Relativized Q")))+
    labs(y="Relativized Light", x="Date (2012)")+
    theme(legend.position = "none",
          panel.background = element_rect(color = "black", fill=NA, size=1),
          axis.text = element_text(size=13),
          axis.title = element_text(size=15)),
  
  align="hv",ncol=1)


ggplot(df, aes(light_rel, GPP))+
  geom_point(size=2)+
  labs(y=expression('GPP (g '*~O[2]~ m^-2~d^-1*')'), x="Light (short-wave radiation) relative to annual max")+
    theme(legend.position = "none",
          panel.background = element_rect(color = "black", fill=NA, size=1),
          axis.text = element_text(size=13),
          axis.title = element_text(size=15))

```

#### First-pass at approximating parameter estimates for different models
```{r}
####################
## Stan data prep ##
####################
rstan_options(auto_write=TRUE)
options(mc.cores=16) #parallel::detectCores())

stan_data_compile <- function(x){
  data <- list(Ndays=length(x$GPP), light = x$light_rel, GPP = x$GPP, GPP_sd = x$GPP_sd,
               tQ = x$tQ, turb = x$mean_daily_turb, depth = x$depth)
  return(data)
}

stan_data <- stan_data_compile(df)

###############################
## Run Stan to get estimates ##
###############################
stan_model_list <- as.list(list.files(pattern = "*.stan"))

stan_model_output_AR <- lapply(stan_model_list[1:2], function(x) stan(x, data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12)))
stan_model_output_Logistic <- lapply(stan_model_list[3:4], function(x) stan(x, data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12)))
stan_model_output_Ricker <- lapply(stan_model_list[5:6], function(x) stan(x, data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12)))
stan_model_output_Ricker_Ladj <- lapply(stan_model_list[7:8], function(x) stan(x, data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12)))
stan_model_output_Gompertz <- lapply(stan_model_list[9:10], function(x) stan(x, data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12)))


# View on shiny
launch_shinystan(stan_model_output) ## Click explore tab when new window opens
# Save Output
saveRDS(stan_model_output_AR,"stan_model_output_AR.rds")
saveRDS(stan_model_output_Logistic,"stan_model_output_Logistic.rds")
saveRDS(stan_model_output_Ricker,"stan_model_output_Ricker.rds")
saveRDS(stan_model_output_Ricker_Ladj,"stan_model_output_Ricker_Ladj.rds")
saveRDS(stan_model_output_Gompertz,"stan_model_output_Gompertz.rds")

## See simulation_matrix_output.R for code to create figures
```


#### Extract median estimate and simulate GPP data (despite poor parameter convergence)
```{r, warning=FALSE}
# source simulation models
source("Simulated_ProductivityModel1_Autoregressive.R") # estimated parameters: phi, alpha, beta, sig_p
source("Simulated_ProductivityModel2_Logistic.R") # estimated parameters: r, K, s, c, sig_p
source("Simulated_ProductivityModel3_Ricker.R") # estimated parameters: r, lambda, s, c, sig_p
source("Simulated_ProductivityModel4_Ricker_lightadj.R") # estimated parameters: alpha_0, alpha_1, lambda, s, c, sig_p
source("Simulated_ProductivityModel5_Gompertz.R") # estimated parameters: beta_0, beta_1, beta_2, s, c, sig_p

## Import fits from previous model outputs
stan_model_output_AR <- readRDS("stan_model_output_AR.rds")
stan_model_output_Logistic <- readRDS("stan_model_output_Logistic.rds")
stan_model_output_Ricker <- readRDS("stan_model_output_Ricker.rds")
stan_model_output_Ricker_Ladj <- readRDS("stan_model_output_Ricker_Ladj.rds")
stan_model_output_Gompertz <- readRDS("stan_model_output_Gompertz.rds")

source("StanParameterExtraction_Source.R")

PM1_medpar <- phenom_extract_medians(rstan::extract(PM1_DataOutput, c("phi","alpha","beta","l_pred_GPP","sig_p")))
PM2_medpar <- mechB_extract_medians(rstan::extract(PM2_DataOutput,c("r","K","s","c","B","P","pred_GPP","sig_p")))
PM3_medpar <- mechB_extract_medians(rstan::extract(PM3_DataOutput, c("r","beta_0","s","c","B","P","pred_GPP","sig_p")))


## Simulate data for each growth model
df$simGPP_PM1 <- PM1(phi=PM1_medpar$par$phi,
                     alpha=PM1_medpar$par$alpha,
                     beta=PM1_medpar$par$beta,
                     sig_p=PM1_medpar$par$sig_p, df=df)
df$simGPP_PM2 <- PM2(r=PM2_medpar$par$r,
                     K=PM2_medpar$par$K,
                     s=PM2_medpar$par$s,
                     c=PM2_medpar$par$c,
                     sig_p=PM2_medpar$par$sig_p, df=df)
df$simGPP_PM3 <- PM3(r=PM3_medpar$par$r,
                     beta_0=PM3_medpar$par$beta_0,
                     s=PM3_medpar$par$s,
                     c=PM3_medpar$par$c,
                     sig_p=PM3_medpar$par$sig_p, df=df)

sim_viz <- function(x, col){
  ggplot(df, aes(date, GPP))+
    geom_point()+
    geom_line(data=df, aes(date, x), color=col)
    #scale_y_continuous(limits = c(0,15))
}

plot_grid(
  #sim_viz(df$simGPP_PM1, "red"),
  #sim_viz(df$simGPP_PM2, "purple"),
  sim_viz(df$simGPP_PM3, "blue"),
ncol=1)

apply(df[,c("GPP","simGPP_PM1","simGPP_PM2","simGPP_PM3")], 2, function(x) rmse(df$GPP, x))

```

#### Recover parameter estimates from simulated data
```{r}
#######################
## Stan data prep v2 ##
#######################
med_simGPP_PM1 <- PM1(phi=PM1_medpar$par$phi,
                  alpha=PM1_medpar$par$alpha,
                  beta=PM1_medpar$par$beta,
                  sig_p=PM1_medpar$par$sig_p,
                  df=df)
med_simGPP_PM2 <- PM2(r=PM2_medpar$par$r,
                  K=PM2_medpar$par$K,
                  s=PM2_medpar$par$s,
                  c=PM2_medpar$par$c,
                  sig_p=PM2_medpar$par$sig_p,
                  df=df)
med_simGPP_PM3 <- PM3(r=PM3_medpar$par$r,
                  beta_0=PM3_medpar$par$beta_0,
                  s=PM3_medpar$par$s,
                  c=PM3_medpar$par$c,
                  sig_p=PM3_medpar$par$sig_p,
                  df=df)

## Compile Stan data
stan_simdat_compile <- function(x, med_simGPP){
  data <- list(Ndays=length(x$GPP), light = x$light_rel, GPP = med_simGPP, tQ = x$tQ, GPP_sd = x$GPP_sd)
  return(data)
}

stan_simdat1 <- stan_simdat_compile(df, med_simGPP_PM1)
stan_simdat2 <- stan_simdat_compile(df, med_simGPP_PM2)
stan_simdat3 <- stan_simdat_compile(df, med_simGPP_PM3)

###############################
## Run Stan to get estimates ##
###############################
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())

simPM1_DataOutput <- stan("Stan_ProductivityModel1_Autoregressive.stan", data=stan_simdat1, chains=3, iter=5000, control=list(max_treedepth=12) )
simPM2_DataOutput <- stan("Stan_ProductivityModel2_Logistic.stan", data=stan_simdat2, chains=3, iter=5000, control=list(max_treedepth=12) )
simPM3_DataOutput <- stan("Stan_ProductivityModel3_Ricker.stan", data=stan_simdat3, chains=3, iter=5000, control=list(max_treedepth=12) )

launch_shinystan(simPM3_DataOutput)

# Save Output
saveRDS(simPM1_DataOutput,"simPM1_DataOutput.rds")
saveRDS(simPM2_DataOutput,"simPM2_DataOutput.rds")
saveRDS(simPM3_DataOutput,"simPM3_DataOutput.rds")
```


## Compare the Input versus Output
```{r}
## Import if needed
PM1_DataOutput <- readRDS("PM1_DataOutput.rds")
PM2_DataOutput <- readRDS("PM2_DataOutput.rds")
PM3_DataOutput <- readRDS("PM3_DataOutput.rds")
simPM1_DataOutput <- readRDS("simPM1_DataOutput.rds")
simPM2_DataOutput <- readRDS("simPM2_DataOutput.rds")
simPM3_DataOutput <- readRDS("simPM3_DataOutput.rds")

## Source parameter extraction and recovery functions
source("StanParameterExtraction_Source.R")
source("PM_Evaluation_Functions.R")

## Input parameters
PM1_medpar <- phenom_extract_medians(rstan::extract(PM1_DataOutput, c("phi","alpha","beta","l_pred_GPP","sig_p")))
PM2_medpar <- mechB_extract_medians(rstan::extract(PM2_DataOutput,c("r","K","s","c","B","P","pred_GPP","sig_p")))
PM3_medpar <- mechB_extract_medians(rstan::extract(PM3_DataOutput,c("r","beta_0","s","c","B","P","pred_GPP","sig_p")))

PM1_par_IN <- c("phi"=PM1_medpar$par$phi,
                "alpha"=PM1_medpar$par$alpha,
                "beta"=PM1_medpar$par$beta,
                "sig_p"=PM1_medpar$par$sig_p)
PM2_par_IN <- c("r"=PM2_medpar$par$r,
                "K"=PM2_medpar$par$K,
                "s"=PM2_medpar$par$s,
                "c"=PM2_medpar$par$c,
                "sig_p"=PM2_medpar$par$sig_p)
PM3_par_IN <- c("r"=PM3_medpar$par$r,
                "beta_0"=PM3_medpar$par$beta_0,
                "s"=PM3_medpar$par$s,
                "c"=PM3_medpar$par$c,
                "sig_p"=PM3_medpar$par$sig_p)

## Output parameters
PM1_par_OUT <- CI_par_PM1(rstan::extract(simPM1_DataOutput))
PM2_par_OUT <- CI_par_PM2(rstan::extract(simPM2_DataOutput))
PM3_par_OUT <- CI_par_PM3(rstan::extract(simPM3_DataOutput))

## Comparison
plot_grid(in_vs_out(PM1_par_IN, PM1_par_OUT,"PM1: GPP"),
          #in_vs_out(PM2_par_IN, PM2_par_OUT,"PM2: Logistic"),
          in_vs_out(PM3_par_IN, PM3_par_OUT,"PM2: Ricker"),
          ncol = 2)
```






```{r}
## OLD CODE



PM1_DataOutput <- stan("Stan_ProductivityModel1_Autoregressive.stan", data=stan_data, chains=3, iter=50, control=list(max_treedepth=12) )
PM2_DataOutput <- stan("Stan_ProductivityModel2_Logistic.stan", data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12) )
PM3_DataOutput <- stan("Stan_ProductivityModel3_Ricker.stan", data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12) )
PM4_DataOutput <- stan("Stan_ProductivityModel4_Ricker_lightadj.stan", data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12) )
PM5_DataOutput <- stan("Stan_ProductivityModel5_Gompertz.stan", data=stan_data, chains=3, iter=5000, control=list(max_treedepth=12) )

```